export interface POSProduct {
  id: string;
  name: string;
  generic: string;
  qty: number;
  sell: number;
  category: string;
  expiry: string;
}

export const PRODUCTS: POSProduct[] = [
  { id:'p1',  name:'ABIDEC DROP',              generic:'Multivitamin Drops',        qty:2,   sell:255,    category:'Paediatrics',     expiry:'2026-12' },
  { id:'p2',  name:'ACICLOVIR 200MG TAB',      generic:'Aciclovir',                 qty:13,  sell:37.50,  category:'Antifungals',     expiry:'2027-03' },
  { id:'p3',  name:'AMOKSICLAV 625MG TAB',     generic:'Amoxicillin+Clavulanate',   qty:84,  sell:150,    category:'Antibiotics',     expiry:'2027-06' },
  { id:'p4',  name:'AMOKSICLAV 1000MG TAB',    generic:'Amoxicillin+Clavulanate',   qty:17,  sell:202.50, category:'Antibiotics',     expiry:'2027-06' },
  { id:'p5',  name:'AMOXYL 250 LETEP',         generic:'Amoxicillin',               qty:98,  sell:4.50,   category:'Antibiotics',     expiry:'2026-09' },
  { id:'p6',  name:'ARTEMETER INJ 80MG',       generic:'Artemether',                qty:52,  sell:7.50,   category:'Injections',      expiry:'2027-01' },
  { id:'p7',  name:'ATESUNATE 120MG INJ',      generic:'Artesunate',                qty:39,  sell:60,     category:'Antimalarials',   expiry:'2027-02' },
  { id:'p8',  name:'AZITHROMYCIN 250MG TAB',   generic:'Azithromycin',              qty:15,  sell:52.50,  category:'Antibiotics',     expiry:'2027-04' },
  { id:'p9',  name:'AZITHROMYCIN 500MG TAB',   generic:'Azithromycin',              qty:60,  sell:60,     category:'Antibiotics',     expiry:'2027-04' },
  { id:'p10', name:'BACLOFEN 10MG TAB',        generic:'Baclofen',                  qty:261, sell:4.50,   category:'Neurology',       expiry:'2027-08' },
  { id:'p11', name:'BEDIMOL INFUSION',         generic:'Paracetamol IV',            qty:71,  sell:75,     category:'Injections',      expiry:'2026-11' },
  { id:'p12', name:'BISOPROLOL 5MG TAB',       generic:'Bisoprolol',                qty:9,   sell:37.50,  category:'Cardiovascular',  expiry:'2027-05' },
  { id:'p13', name:'BUSCOPAN INJ',             generic:'Hyoscine Butylbromide',     qty:90,  sell:15,     category:'Injections',      expiry:'2027-03' },
  { id:'p14', name:'CAFERGOT TAB',             generic:'Ergotamine+Caffeine',       qty:47,  sell:15,     category:'Neurology',       expiry:'2027-01' },
  { id:'p15', name:'CALPOL INFANT SYRUP',      generic:'Paracetamol Syrup',         qty:6,   sell:180,    category:'Paediatrics',     expiry:'2026-10' },
  { id:'p16', name:'CEFTRIAXONE 1G INJ',       generic:'Ceftriaxone',               qty:239, sell:37.50,  category:'Injections',      expiry:'2027-06' },
  { id:'p17', name:'CEFUROXIME 500MG TAB',     generic:'Cefuroxime',                qty:24,  sell:150,    category:'Antibiotics',     expiry:'2027-05' },
  { id:'p18', name:'CELECOXIB 200MG CAP',      generic:'Celecoxib',                 qty:25,  sell:75,     category:'Analgesics',      expiry:'2027-07' },
  { id:'p19', name:'CLINDAMYCIN 300MG CAP',    generic:'Clindamycin',               qty:91,  sell:67.50,  category:'Antibiotics',     expiry:'2027-04' },
  { id:'p20', name:'COARTEM TAB',              generic:'Artemether+Lumefantrine',   qty:8,   sell:180,    category:'Antimalarials',   expiry:'2026-12' },
  { id:'p21', name:'COARTEM PAEDIATRIC',       generic:'Artemether+Lumefantrine',   qty:2,   sell:75,     category:'Paediatrics',     expiry:'2026-12' },
  { id:'p22', name:'CODE FREE STRIP',          generic:'Glucose Test Strip',        qty:157, sell:15,     category:'Diabetes',        expiry:'2027-01' },
  { id:'p23', name:'DAPAGLIFLOZIN 10MG',       generic:'Dapagliflozin',             qty:42,  sell:270,    category:'Diabetes',        expiry:'2027-09' },
  { id:'p24', name:'DICLOFENAC 50MG TAB',      generic:'Diclofenac Sodium',         qty:4,   sell:7.50,   category:'Analgesics',      expiry:'2027-02' },
  { id:'p25', name:'DICLOFENAC INJ 75MG',      generic:'Diclofenac Sodium',         qty:17,  sell:4.50,   category:'Injections',      expiry:'2027-02' },
  { id:'p26', name:'DOXYCAP 100MG',            generic:'Doxycycline',               qty:92,  sell:30,     category:'Antibiotics',     expiry:'2027-03' },
  { id:'p27', name:'ESKAGYL 400MG TAB',        generic:'Metronidazole',             qty:89,  sell:7.50,   category:'Antibiotics',     expiry:'2027-05' },
  { id:'p28', name:'FLAGYL LETAP 200MG',       generic:'Metronidazole',             qty:17,  sell:3,      category:'Antibiotics',     expiry:'2027-04' },
  { id:'p29', name:'FLUCORON 150MG CAP',       generic:'Fluconazole',               qty:302, sell:15,     category:'Antifungals',     expiry:'2027-08' },
  { id:'p30', name:'FOLIC ACID LETAP',         generic:'Folic Acid',                qty:32,  sell:0.75,   category:'Vitamins',        expiry:'2027-06' },
  { id:'p31', name:'FUROSEMIDE 40MG TAB',      generic:'Furosemide',                qty:2,   sell:60,     category:'Cardiovascular',  expiry:'2027-01' },
  { id:'p32', name:'GENTAMYCIN INJ',           generic:'Gentamicin',                qty:85,  sell:7.50,   category:'Injections',      expiry:'2027-03' },
  { id:'p33', name:'GLUCANIX-MET 50/1000MG',   generic:'Vildagliptin+Metformin',    qty:44,  sell:375,    category:'Diabetes',        expiry:'2027-07' },
  { id:'p34', name:'HYDROCORT INJECTION',      generic:'Hydrocortisone',            qty:19,  sell:18,     category:'Injections',      expiry:'2027-02' },
  { id:'p35', name:'IVERMECTIN TAB 3MG',       generic:'Ivermectin',                qty:304, sell:4.50,   category:'Antiparasitics',  expiry:'2027-09' },
  { id:'p36', name:'LEVOFLOXACIN 500MG TAB',   generic:'Levofloxacin',              qty:14,  sell:105,    category:'Antibiotics',     expiry:'2027-05' },
  { id:'p37', name:'LUFART DS TAB',            generic:'Artemether+Lumefantrine',   qty:73,  sell:60,     category:'Antimalarials',   expiry:'2027-01' },
  { id:'p38', name:'LYDIA P CONTRA',           generic:'Levonorgestrel',            qty:67,  sell:30,     category:'Contraceptives',  expiry:'2027-06' },
  { id:'p39', name:'MALARIA TEST KIT',         generic:'RDT Malaria',               qty:124, sell:37.50,  category:'OTC',             expiry:'2027-03' },
  { id:'p40', name:'METFORMIN 500MG',          generic:'Metformin HCl',             qty:8,   sell:7.50,   category:'Diabetes',        expiry:'2027-04' },
  { id:'p41', name:'METRONIDAZOLE SYRUP',      generic:'Metronidazole',             qty:25,  sell:30,     category:'Paediatrics',     expiry:'2027-02' },
  { id:'p42', name:'MORPHINE INJ',             generic:'Morphine Sulfate',          qty:63,  sell:60,     category:'Analgesics',      expiry:'2027-05' },
  { id:'p43', name:'NEXIUM 40MG TAB',          generic:'Esomeprazole',              qty:18,  sell:480,    category:'Gastrointestinal',expiry:'2027-08' },
  { id:'p44', name:'NIFECARD XL 30MG TAB',     generic:'Nifedipine',                qty:12,  sell:150,    category:'Cardiovascular',  expiry:'2027-06' },
  { id:'p45', name:'OMEPRAZOLE INJ 40MG',      generic:'Omeprazole',                qty:36,  sell:37.50,  category:'Injections',      expiry:'2027-04' },
  { id:'p46', name:'PARACETAMOL EXETER TAB',   generic:'Paracetamol',               qty:260, sell:7.50,   category:'Analgesics',      expiry:'2027-09' },
  { id:'p47', name:'PARACETAMOL LATAMOL',      generic:'Paracetamol',               qty:109, sell:1.50,   category:'Analgesics',      expiry:'2027-09' },
  { id:'p48', name:'PENICILLIN V TAB',         generic:'Phenoxymethylpenicillin',   qty:76,  sell:3.75,   category:'Antibiotics',     expiry:'2027-03' },
  { id:'p49', name:'PETHIDINE INJ',            generic:'Pethidine HCl',             qty:37,  sell:105,    category:'Analgesics',      expiry:'2027-06' },
  { id:'p50', name:'POSTINOR 2 ORIGINAL',      generic:'Levonorgestrel',            qty:4,   sell:180,    category:'Contraceptives',  expiry:'2027-01' },
  { id:'p51', name:'PREDNISOLONE TAB 5MG',     generic:'Prednisolone',              qty:15,  sell:2.25,   category:'Hormones',        expiry:'2027-05' },
  { id:'p52', name:'PREGNANCY TEST KIT',       generic:'hCG Test',                  qty:71,  sell:7.50,   category:'OTC',             expiry:'2027-08' },
  { id:'p53', name:'PROCAIN PENICILLINE INJ',  generic:'Procaine Penicillin',       qty:11,  sell:12,     category:'Injections',      expiry:'2027-02' },
  { id:'p54', name:'RAPINOL TAB',              generic:'Allopurinol',               qty:81,  sell:2.25,   category:'Analgesics',      expiry:'2027-07' },
  { id:'p55', name:'RETARDINE XL 30MG',        generic:'Nifedipine XL',             qty:28,  sell:60,     category:'Cardiovascular',  expiry:'2027-04' },
  { id:'p56', name:'ROBB OINTMENT',            generic:'Methyl Salicylate',         qty:241, sell:4.50,   category:'Dermatology',     expiry:'2027-10' },
  { id:'p57', name:'ROCEPHIN INJ 1G',          generic:'Ceftriaxone',               qty:6,   sell:300,    category:'Injections',      expiry:'2027-03' },
  { id:'p58', name:'SALBUTAMOL NEBULES 5MG',   generic:'Salbutamol',                qty:5,   sell:15,     category:'Respiratory',     expiry:'2027-01' },
  { id:'p59', name:'SYRINGE 10CC',             generic:'Disposable Syringe',        qty:258, sell:3,      category:'Surgical',        expiry:'2028-01' },
  { id:'p60', name:'SYRINGE 2CC',              generic:'Disposable Syringe',        qty:27,  sell:1.50,   category:'Surgical',        expiry:'2028-01' },
  { id:'p61', name:'TOBLIS JELLY SACHET',      generic:'Lubricant Jelly',           qty:53,  sell:7.50,   category:'Surgical',        expiry:'2027-06' },
  { id:'p62', name:'TRANEXAMIC ACID INJ',      generic:'Tranexamic Acid',           qty:4,   sell:90,     category:'Haematology',     expiry:'2027-04' },
  { id:'p63', name:'TYPHOID TEST KIT',         generic:'Widal Test',                qty:16,  sell:75,     category:'OTC',             expiry:'2027-02' },
  { id:'p64', name:'ULCIRON SUSPENSION',       generic:'Sucralfate',                qty:59,  sell:45,     category:'Gastrointestinal',expiry:'2027-05' },
  { id:'p65', name:'VENTOLIN INHALER',         generic:'Salbutamol',                qty:2,   sell:180,    category:'Respiratory',     expiry:'2027-03' },
  { id:'p66', name:'VITAMIN B DENK TAB',       generic:'Vitamin B Complex',         qty:39,  sell:75,     category:'Vitamins',        expiry:'2027-08' },
  { id:'p67', name:'VITAMIN B COMPLEX INJ',    generic:'Vitamin B Complex',         qty:32,  sell:15,     category:'Vitamins',        expiry:'2027-06' },
  { id:'p68', name:'WOODS ANTITUSIVE',         generic:'Dextromethorphan',          qty:18,  sell:90,     category:'Respiratory',     expiry:'2027-04' },
  { id:'p69', name:'WOODS EXPECTORANTS',       generic:'Guaifenesin',               qty:18,  sell:90,     category:'Respiratory',     expiry:'2027-04' },
  { id:'p70', name:'ZITHROMAX CAPSULES 250MG', generic:'Azithromycin',              qty:7,   sell:300,    category:'Antibiotics',     expiry:'2027-05' },
  { id:'p71', name:'ZYMAX 500MG CAP',          generic:'Azithromycin',              qty:83,  sell:60,     category:'Antibiotics',     expiry:'2027-06' },
  { id:'p72', name:'AMLODIPINE 10MG TEVA',     generic:'Amlodipine',                qty:6,   sell:30,     category:'Cardiovascular',  expiry:'2027-07' },
  { id:'p73', name:'AMLODIPINE 5MG TEVA',      generic:'Amlodipine',                qty:5,   sell:22.50,  category:'Cardiovascular',  expiry:'2027-07' },
  { id:'p74', name:'ATORVASTATIN 10MG TEVA',   generic:'Atorvastatin',              qty:3,   sell:60,     category:'Cardiovascular',  expiry:'2027-06' },
  { id:'p75', name:'AUGMENTIN SUSP 457',       generic:'Amoxicillin+Clavulanate',   qty:5,   sell:270,    category:'Paediatrics',     expiry:'2026-11' },
  { id:'p76', name:'AUGMENTIN TAB 1G',         generic:'Amoxicillin+Clavulanate',   qty:6,   sell:480,    category:'Antibiotics',     expiry:'2027-06' },
  { id:'p77', name:'ANTI TETANUS SERUM',       generic:'Tetanus Antitoxin',         qty:12,  sell:60,     category:'Injections',      expiry:'2027-01' },
  { id:'p78', name:'ASPIRIN CARDIO',           generic:'Aspirin 75mg',              qty:4,   sell:75,     category:'Cardiovascular',  expiry:'2027-08' },
  { id:'p79', name:'CHLORAMPHENICOL 250MG',    generic:'Chloramphenicol',           qty:29,  sell:7.50,   category:'Antibiotics',     expiry:'2027-03' },
  { id:'p80', name:'GLIBINIL 5MG',             generic:'Glibenclamide',             qty:6,   sell:3,      category:'Diabetes',        expiry:'2027-05' },
  { id:'p81', name:'ACTILIFE CAPS',            generic:'Multivitamin',              qty:16,  sell:75,     category:'Vitamins',        expiry:'2027-06' },
  { id:'p82', name:'ALBENDAZOLE 400MG TAB',    generic:'Albendazole',               qty:22,  sell:7.50,   category:'Antiparasitics',  expiry:'2027-05' },
  { id:'p83', name:'ANCIGEL O SUSP',           generic:'Metronidazole+Norfloxacin', qty:63,  sell:90,     category:'Gastrointestinal',expiry:'2027-03' },
  { id:'p84', name:'ANCIGEL TABLET',           generic:'Metronidazole+Norfloxacin', qty:14,  sell:15,     category:'Gastrointestinal',expiry:'2027-03' },
  { id:'p85', name:'CARBIMAZOLE TAB',          generic:'Carbimazole',               qty:6,   sell:45,     category:'Hormones',        expiry:'2027-04' },
  { id:'p86', name:'CEFUROXIME INJ 750MG',     generic:'Cefuroxime',                qty:17,  sell:43.50,  category:'Injections',      expiry:'2027-05' },
  { id:'p87', name:'CIPROTAB TZ',              generic:'Ciprofloxacin+Tinidazole',  qty:6,   sell:45,     category:'Antibiotics',     expiry:'2027-02' },
  { id:'p88', name:'KWIK ACTION',              generic:'Paracetamol+Caffeine',      qty:15,  sell:3,      category:'Analgesics',      expiry:'2027-06' },
  { id:'p89', name:'NOVACIP 500MG TAB',        generic:'Ciprofloxacin',             qty:6,   sell:15,     category:'Antibiotics',     expiry:'2027-03' },
  { id:'p90', name:'REDSUN CONDOM',            generic:'Male Condom',               qty:13,  sell:7.50,   category:'Surgical',        expiry:'2028-06' },
  { id:'p91', name:'ZULU MR TAB',              generic:'Tramadol',                  qty:26,  sell:22.50,  category:'Analgesics',      expiry:'2027-04' },
  { id:'p92', name:'BENZYL PENICILLINE INJ',   generic:'Benzylpenicillin',          qty:2,   sell:3.75,   category:'Injections',      expiry:'2027-01' },
  { id:'p93', name:'PARA TAB TOBINCO',         generic:'Paracetamol',               qty:73,  sell:3,      category:'Analgesics',      expiry:'2027-08' },
  { id:'p94', name:'AMIKACIN INJ UK',          generic:'Amikacin',                  qty:11,  sell:75,     category:'Injections',      expiry:'2027-02' },
  { id:'p95', name:'ACNERON CREAM',            generic:'Tretinoin Cream',           qty:3,   sell:22.50,  category:'Dermatology',     expiry:'2027-05' },
  { id:'p96', name:'ABONIIKI BALM 2',          generic:'Herbal Balm',               qty:4,   sell:15,     category:'Dermatology',     expiry:'2027-09' },
];

export const CATEGORIES = [
  'All','Analgesics','Antibiotics','Antimalarials','Cardiovascular',
  'Diabetes','Respiratory','Vitamins','Antifungals','Gastrointestinal',
  'Neurology','Hormones','Haematology','Antiparasitics','OTC',
  'Injections','Surgical','Dermatology','Contraceptives','Paediatrics',
];
